Skip shellcheck on Windows
MentorMate/node-pipeline-template pull request #24
Opened 2022-10-31 00:36 UTC by Yavorss

2022-10-31 09:32 UTC, IvayloGrahlyov approved these changes

2022-10-31 15:41 UTC, g-nevenov reviewed
@Yavorss please review the merge conflicts.

2022-11-05 12:52 UTC, IvayloGrahlyov approved these changes

2022-11-15 11:37 UTC, g-nevenov approved these changes

2022-11-22 14:14 UTC, g-nevenov requested changes
Could you please resolve the merge conflicts so we can merge the branch?

2022-11-24 09:29 UTC, g-nevenov approved these changes

2022-11-24 09:32 UTC, merged